name: CI
on:
  push: {}

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v6

      - name: Setup the go toolchain
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build the project
        run: go build .

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: binary
          path: justtrustme
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-slim
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    permissions:
      contents: write
      id-token: write
      attestations: write
    needs:
      - build
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v6

      - name: Download the built binary
        uses: actions/download-artifact@v5
        with:
          name: binary

      - name: Attest the built binary
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: justtrustme
          show-summary: false

      - name: Publish the release
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            --target "${GITHUB_SHA}" \
            --title "Deployment ${GITHUB_REF_NAME}" \
            --notes "Automatically published release, no changelog available." \
            --latest \
            justtrustme # Artifact to upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
